steps:
  # Build the Maven project
  - name: 'maven:3.9.6-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
    dir: '.' # Assuming pom.xml is in the root of api_sazon_bueno

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/hip-host-465019-n7/sazondelbueno-repo/api-sazondelbueno:$COMMIT_SHA', '.']
    dir: '.' # Assuming Dockerfile is in the root of api_sazon_bueno

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/hip-host-465019-n7/sazondelbueno-repo/api-sazondelbueno:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-sazondelbueno'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/hip-host-465019-n7/sazondelbueno-repo/api-sazondelbueno:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Adjust as needed for authentication
    entrypoint: 'gcloud'

options:
  logging: CLOUD_LOGGING_ONLY

